### ISSUE TITLE
Change default cluster color to a single color

### ISSUE THREAD

**Issue by MappingKat** [nationalparkservice/npmap.js#160]
Mamata brought up a good point in that different colored clusters don't make sense with one dataset.  I think we should figure out a way to only have one color clusters with one dataset and multiple colors with two or more... 

Not a priority but worth noting

**Comment by jduggan1** [comment]
This seems related to an issue I'm currently having.  I have three geojson layers (one each for species), and am attempting to create marker clusters for each species with different colors so that users can easily spot the different species.

However, the color of the marker clusters is always the color of the last layer added.  For example, if I add a blue cluster layer, then a green cluster layer, then a black cluster layer, the color of all of the clusters is black.  I would like to use marker clusters as otherwise there are so many markers that the visualization is both cluttered and unresponsive.

Is this the right issue for this (should I open a new one), or is this already supported?  If the latter, are there any examples of this?

**Comment by nateirwin** [comment]
Hi @jduggan1: After re-reading your comment, I believe what you are seeing is a bug. I just opened a new ticket to track it: https://github.com/nationalparkservice/npmap.js/issues/239.
