### ISSUE TITLE
Connect NPMap.js Search to X-Ray View basemap on insidemaps

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/npmap.js#261]
Right now, searching for a park works wonderfully in the Places Editor, but the search bar in maps using NPMap.js is still pulling from a static (and out-of-date) JSON file. We need to either devise a system for updating this JSON file regularly from the CartoDB table, or connecting the search more dynamically to cartodb (for example, hitting the api to request that JSON table on load).

This issue came to my attention based on an email from someone who couldn't find his parks in the X-Ray Map. The three missing parks are:
- Frederick Law Olmsted NHS (FRLA)
- John Fitzgerald Kennedy Birthplace NHS (JOFI)
- Longfellow House Washington Headquarters NHS (LONG)

There are likely a few other parks missing from the NPMap.js search. Some may be missing that were never stored as polygons originally, so this would be a good place to start looking. Regardless, this would work better if the list was build off the latest version of our boundaries table.

**Comment by cwlawlis802** [comment]
Hm, so I am slightly confused here - this may be a bit misinterpreted?

Park Tiles is currently hooked up to NPMap.js 3.0.0, which is hooked into our CartoDB boundaries table. Park Tiles is able to find both FRLA and LONG via search. It can also find JOFI, but it's labeled "John F Kennedy National Historic Site", which is line with http://www.nps.gov/jofi/index.htm.

In terms of Places Editor search, are you referring to the dropdown menu? Each park appears the same way in the Places Editor dropdown as it does in Park Tiles search, so I can't identify an issue here.

According to @jimmyrocks, Places Editor currently excludes parks without polygons from the dropdown list, so this may be the issue you're referring to in that regard.

It appears the X-Ray map on http://insidemaps.nps.gov/places/ is not hooked up to NPMap.js 3.0.0, which is preventing search from finding these parks.

So, NPMap.js is not the issue here, we need to hook these maps into NPMap.js to solve this issue.

**Comment by cwlawlis802** [comment]
Regardless of the successful search via NPMap.js for these parks, we may still need to hook it up to the new boundaries table if we are altering this from the current one in CartoDB.

**Comment by mtaylorlong** [comment]
Ah, okay – this is much simpler than I thought. The only issue, then, is with the search bar in that little X-Ray Map on the Places page. If it's updated to the NPMap.js v3, it sounds like it'll work fine.

**Comment by cwlawlis802** [comment]
:+1: will do.

**Comment by nateirwin** [comment]
Fixed.

**Comment by cwlawlis802** [comment]
Updated here: https://github.com/nationalparkservice/npmap-website/blob/master/dev/npmap/places-x-ray-embed/assets/js/app.js#L48.
